name: Update Guesses

on:
  push:
    paths:
      - "data/frequency.json"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_guesses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Fetch latest lottery results
        timeout-minutes: 1
        run: |
          python scripts/fetch_latest.py

      - name: Update frequency
        run: |
          python scripts/update_frequency.py

      - name: Update next guesses
        run: |
          python scripts/update_guesses.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/latest_lottery_result.json data/frequency.json data/next_guess.json
          git commit -m 'Update lottery results, frequency, and next guesses'
          git push
